### ISSUE TITLE
iOS Game Crash

### ISSUE THREAD

**Issue by SwordStroker** [Akue/LSky#1]
Hello there,
I've implemented this asset into our game.Builded for ios mobile and the game is crashing.
I've deleted scripts folder,and made another build,it did not crashed.
So i assume  some of the scripts causing a crash.

I'm also trying to figure out which one :).If i solve it,i'll let you know.

----- Update -----
Ok,i've did some tests..Our game is using udp sockets.Everything is ok but when i disconnect from current server,the app crashes.I've deleted the scripts of the asset,and it didnt crashed.
Do you have any idea what's causing that ?
What can affect the disconnect procedure its strange :/

**Comment by Akue** [comment]
Hello, I'm not sure what can happen, the asset is not tested on mobile devices.

For now this asset is obsolete, but at some time will be available a new asset 

To be honest I did version 2.0 on a free afternoon, however the new asset is something serious, so I will take the time to test on the most devices

**Comment by SwordStroker** [comment]
Hello there,
It turned out to be a bug in Unity.. And its submitted as a bug,they are going to fix it in future releases :).
Its cause of .net 4.6,i downgraded it to 3.5 and all works fine in mobile now :)
